# Етап 1 – build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore ./OnlineDoctorProject/OnlineDoctorProject.csproj
RUN dotnet publish ./OnlineDoctorProject/OnlineDoctorProject.csproj -c Release -o /app/out

# Етап 2 – runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "OnlineDoctorProject.dll"]
