# Билд етап
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish ./vikiDiplomen/vikiDiplomen.csproj -c Release -o /app/out

# Runtime етап
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "vikiDiplomen.dll"]